#cloud-config
# Proxmox 8.4 Debian 13 Generic Cloud qcow2 Template Setup
# VERSION: 1.0.10
# LAST EDIT: Oct 31, 2025
# Foundry VTT VM Configuration

# Basic VM configuration
hostname: debian13-fvtt-template-dev
timezone: America/Vancouver

# Boot commands (run very early in boot process)
bootcmd:
  - echo "Boot phase - waiting for network interfaces..." >> /root/setup.log
  - timeout 30 sh -c 'until ip link show | grep -q "state UP"; do sleep 1; done' || echo "Network interface timeout" >> /root/setup.log

# User configuration
users:
  - name: manager
    groups: [sudo]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    passwd: '$6$EtqCPBKrPwPLXTWN$SPmsF7Nh2r/2qEZrWZqrRMKaTiJ6ABJ3fLc60Ouu8Js9YWidRUX5.JL1m/tV7dajUzvc18ISFShkeM81ICGlN1'
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILXC8ewQSURYdaH6TWS0/Pv6KGY2tYap7t1eAizeQjKY brad@dev1
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFK+9vVSQ3PsS5EmZoZDhnwPCl05Z/XdZ8xpG6HijOQX common-jan25
  - name: fvtt
    shell: /usr/sbin/nologin
    system: true

# Package management
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - htop
  - nfs-common
  - s3cmd
  - zip
  - ufw

# File system setup
# Use whole disk without partitions
fs_setup:
  - label: fvtt-data
    filesystem: ext4
    device: /dev/sdb
    overwrite: true

mounts:
  - ["/dev/sdb", "/home/fvtt/data", "ext4", "defaults", "0", "2"]
  # swap file setup (non partition based)

swap:
  filename: /swapfile
  size: 1G
  maxsize: 1G

# Write files to system
write_files:
  # WebDAV configuration
  - path: /home/fvtt/webdav/config.yaml
    content: |
      address: 0.0.0.0
      port: 3030
      prefix: /
      behindProxy: true
      directory: /home/fvtt/data/foundrydata
      permissions: CRUD
      users:
      - username: "place#username"
        password: "place#password"
    permissions: '0644'
    owner: fvtt:fvtt
    defer: true

  # WebDAV systemd service
  - path: /etc/systemd/system/webdav.service
    content: |
      [Unit]
      Description=WebDAV Server
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=simple
      User=fvtt
      Group=fvtt
      ExecStart=/usr/bin/webdav --config /home/fvtt/webdav/config.yaml
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    permissions: '0644'
    defer: true

  # Data drive resize service
  - path: /etc/systemd/system/resize-sdb.service
    content: |
      [Unit]
      Description=Resize /dev/sdb and filesystem to fill the disk
      DefaultDependencies=no
      Before=local-fs-pre.target
      Wants=local-fs-pre.target

      [Service]
      User=root
      Group=root
      Type=oneshot
      ExecStart=/usr/sbin/resize2fs /dev/sdb
      RemainAfterExit=yes

      [Install]
      WantedBy=local-fs.target
    permissions: '0644'
    defer: true

  # System environment variables
  - path: /etc/environment
    content: |
      # System wide env values

      ############ Foundry Server #########################

      LEVEL=planlevel
      NODE_ENV=dev

      ####################################################
    permissions: '0644'
    append: true
    defer: true

  # Global shell aliases
  - path: /etc/profile.d/custom-aliases.sh
    content: |
      # Custom system-wide aliases
      alias ll='ls -la'
    permissions: '0644'
    defer: true

  # Root shell aliases (root doesn't always source profile.d)
  - path: /root/.bashrc
    content: |
      
      # Custom aliases for root
      alias ll='ls -la'
    permissions: '0644'
    append: true
    defer: true

  # Unattended upgrades configuration
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Origins-Pattern {
              "origin=Debian,codename=${distro_codename},label=Debian";
              "origin=Debian,codename=${distro_codename},label=Debian-Security";
              "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";
      };
      Unattended-Upgrade::Package-Blacklist {};
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "03:00";
    permissions: '0644'
    defer: true

  # Root crontab file
  - path: /var/spool/cron/crontabs/root
    content: |
      # Foundry VTT VM cron jobs
      # Clean up old log files monthly
      0 2 1 * * /usr/bin/find /var/log -name '*.gz' -type f -delete
      # Monitor script every 5 minutes
      */5 * * * * /root/monitor.sh >/dev/null 2>&1
    permissions: '0600'
    owner: root:crontab
    defer: true

# Commands to run during cloud-init
runcmd:
  # Wait for network to be fully available before proceeding
  - |
    echo "Waiting for network connectivity..." >> /root/setup.log
    MAX_RETRIES=60
    RETRY_COUNT=0
    while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
      # Test both route and actual connectivity
      if ip route get 1.1.1.1 >/dev/null 2>&1 && ping -c 1 1.1.1.1 >/dev/null 2>&1; then
        echo "Network connectivity confirmed after $RETRY_COUNT attempts" >> /root/setup.log
        break
      fi
      RETRY_COUNT=$((RETRY_COUNT + 1))
      echo "Network not ready, attempt $RETRY_COUNT/$MAX_RETRIES" >> /root/setup.log
      sleep 2
    done
    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
      echo "WARNING: Network connectivity timeout after $MAX_RETRIES attempts" >> /root/setup.log
    fi

  # Create directory structure for fvtt (includes home directory creation)
  - mkdir -p /home/fvtt/data/foundrydata/Config
  - mkdir -p /home/fvtt/data/foundrydata/Data
  - mkdir -p /home/fvtt/data/foundrydata/Logs
  - mkdir -p /home/fvtt/data/foundrycore
  - mkdir -p /home/fvtt/webdav
  - chown -R fvtt:fvtt /home/fvtt/

  # Ufw Configuration

  # Download and install WebDAV server
  - cd /tmp
  - wget -q https://github.com/hacdias/webdav/releases/download/v5.8.0/linux-amd64-webdav.tar.gz
  - tar -xzf linux-amd64-webdav.tar.gz
  - mv webdav /usr/bin/
  - rm -f linux-amd64-webdav.tar.gz

  # Download and install Node.js
  - cd /tmp
  - wget -q https://nodejs.org/download/release/v25.0.0/node-v25.0.0-linux-x64.tar.gz
  - tar -xzf node-v25.0.0-linux-x64.tar.gz
  - mv node-v25.0.0-linux-x64/bin/node /usr/bin/
  - rm -rf node-*

  # Configure unattended upgrades
  - dpkg-reconfigure -fnoninteractive unattended-upgrades

  # Register VM with vmapi service
  - |
    systemctl start qemu-guest-agent
    # Wait for qemu-guest-agent to be ready with retry logic
    MAX_RETRIES=30
    RETRY_COUNT=0
    while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
      if systemctl is-active --quiet qemu-guest-agent; then
        echo "qemu-guest-agent is active after $RETRY_COUNT attempts" >> /root/vmapi_registration.log
        break
      fi
      RETRY_COUNT=$((RETRY_COUNT + 1))
      echo "Waiting for qemu-guest-agent... attempt $RETRY_COUNT/$MAX_RETRIES" >> /root/vmapi_registration.log
      sleep 2
    done
    
    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
      echo "Failed to confirm qemu-guest-agent is ready after $MAX_RETRIES attempts" >> /root/vmapi_registration.log
      exit 0
    fi
    
    # Get IP from primary network interface
    INTERFACE=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'dev \K\S+' | head -n1)
    if [ -n "$INTERFACE" ]; then
      VM_IP=$(ip addr show "$INTERFACE" | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)
      if [ -n "$VM_IP" ]; then
        curl -s -G "http://nodeport2.vm.lan:31002/vm/webhook-init" --data-urlencode "ip=$VM_IP" >> /root/vmapi_registration.log 2>&1 || echo "Failed to register with vmapi service" >> /root/vmapi_registration.log
      else
        echo "Failed to get IP address from interface $INTERFACE" >> /root/vmapi_registration.log
      fi
    else
      echo "Failed to find network interface" >> /root/vmapi_registration.log
    fi

  # Enable and start services
  - systemctl daemon-reload
  
  # Enable network wait service
  - systemctl enable systemd-networkd-wait-online.service
  
  # Other services
  - systemctl enable --now webdav.service
  - systemctl enable resize-sdb.service

  # Clean up package cache
  - apt autoremove -y
  - apt autoclean

  # Check if reboot is required after package upgrades
  - |
    if [ -f /var/run/reboot-required ]; then
      echo "Reboot required after package upgrades" >> /root/setup.log
      shutdown -r +1 "Rebooting after cloud-init setup"
    fi
